In [92]:
import numpy as np

#1. Generar un array aleatorio de 100 elementos. Calcular la Mediana correspondiente:

np_random_dim = np.random.randint(150,size=(100))
print(np_random_dim)

np.median(np_random_dim)

[ 52  42  26  44  35  90  75 136 111 126 106  55  85  52  26  98  62  93
  42  80 142  81 142  12  38 113 148 116  98 118 115  59 126 128  59 117
 124  16  35  38 137 127  99 143  46 147   2 128  17  84  45  67  98  39
  55   9 105 131 145   5 121 148 102  93  12 102  45 103  63 146  99  91
  66  40  38  50 143  40  82 148 124 134  71 141  87  86  14  88  46  33
 123  33  31  46   4  17  93  33  36  18]


83.0

In [61]:
#2. Generar un array que contenga siempre valor 1 en sus elementos y que tenga 20 elementos, luego otro array de rango 1 hasta el 20 inclusive. Sumarlos y luego decirme cuál es el Promedio del array resultante:

np_relleno = np.full(20,1)
print(np_relleno)

np_rango = np.arange(1,21)
print(np_rango)

np_suma = np_relleno + np_rango
print(np_suma)

np_suma.mean()


[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


11.5

In [91]:
#3. En base al array del ajedrez generado en esta diapositiva, hacer un cambio de forma (reshape), y que sea de 4 filas x 16 columnas. Calcular su Desvío Estándar

np.arange(1,65)
print(np.arange(1,65))

np_new = np.arange(1,65).reshape(8,8)
print(np_new)

np_new2 = np_new.reshape(4,16)
print(np_new2)

np.std(np_new2)

#Nota: El original es de 1 x 65, y luego pide cambiarlo a 8 x 8. Por eso hice ambos pasos.


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]]


18.472953201911167